name: Deploy Storyline from temp to main (via PR)

on:
  push:
    branches:
      - temp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout temp branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Storyline export
        run: |
          mkdir deploy
          cp -r docs/* deploy/
          cd deploy
          mv story.html index.html
          cd ..

      - name: Copy deploy files to repo root
        run: |
          rm -rf index.html story_content html5 mobile analytics-frame.html meta.xml
          cp -r deploy/* .

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          commit-message: "Deploy Storyline to main [skip ci]"
          title: "Deploy Storyline to main"
          body: |
            Automated PR to deploy Storyline content from `temp` to `main`.

            Includes:
            - index.html
            - story_content/
            - html5/
            - mobile/
            - analytics-frame.html
            - meta.xml
